export const GET_ACCOUNTS_REQUEST = 'GET_ACCOUNTS_REQUEST'
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS'
export const SET_DISPLAYED_ACCOUNT = 'SET_DISPLAYED_ACCOUNT'

export const ACCOUNTS_ERROR = 'ACCOUNTS_ERROR'

export const MONEY_TRANSFER_REQUEST = 'MONEY_TRANSFER_REQUEST'
export const MONEY_TRANSFER_SUCCESS = 'MONEY_TRANSFER_SUCCESS'

export const FILL_ACCOUNT_REQUEST = 'FILL_ACCOUNT_REQUEST'
export const FILL_ACCOUNT_SUCCESS = 'FILL_ACCOUNT_SUCCESS'
