export const GET_ACCOUNTS_REQUEST = 'GET_ACCOUNTS_REQUEST'
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS'
export const GET_ACCOUNTS_ERROR = 'GET_ACCOUNTS_ERROR'
export const SET_DISPLAYED_ACCOUNT = 'SET_DISPLAYED_ACCOUNT'
